/*
 * This source file was generated by the Gradle 'init' task
 */
package tubes;

import java.util.ArrayList;
import java.util.List;

import tubes.models.AlatMusik;
import tubes.models.Pemusik;

public class App {

    public static List<List<Pemusik>> jadwal = new ArrayList<>(); // Array 2D buat nyimpen pemusik di masing masing minggu
    public static List<Pemusik> pemusik = new ArrayList<>(); // Array 2D buat nyimpen pemusik ini bisa alat musik apa aja
    public static List<AlatMusik> alatMusik = new ArrayList<>(); // Array buat nyimpen alat musik
    public static List<Boolean> statusPemusik = new ArrayList<>(); // Array buat nyimpen status dari pemusik di 1 minggu 

    public static void initializeStatusPemusik() {
        for (int i = 0; i < alatMusik.size(); i++) {
            statusPemusik.add(false);
        }
    }

    public static void getNamaMusikYangBelumTerisi() {
        for (int i = 0; i < statusPemusik.size(); i++) {
            if (statusPemusik.get(i) == false) {
                System.out.println(alatMusik.get(i).getNamaAlat() + " tidak berhasil ditemukan!");
            }
        }
    }

    public static int getIndexMusik(AlatMusik alatMusik) {
        switch (alatMusik.getNamaAlat()) {
            case "Gitar":
                return 0;
            case "Bass":
                return 1;
            case "Drum":
                return 2;
            case "Keyboard":
                return 3;
            default:
                throw new AssertionError("Unexpected value: " + alatMusik.getNamaAlat());
        }
    }

    public static boolean isOccupiedForaWeek(){
        for (int i = 0; i < statusPemusik.size(); i++) {
            if (statusPemusik.get(i) == false) {
                return false;
            }
        }
        return true;
    }

    public static void getJadwalForaWeek(int index) {
        if (isOccupiedForaWeek()) {
            System.out.println("--- Proses Penjadwalan Minggu 1 Selesai ---");
            return;
        }

        if (index == pemusik.size()) {
            getNamaMusikYangBelumTerisi();
            return;
            
        }

        boolean forPrint = true;
        int tempPlural = pemusik.get(index).getAlatMusik().size();
        int tempIndex = getIndexMusik(pemusik.get(index).getAlatMusik().get(0)); // Buat ngambil index alat musik dari pemusik disini
        if (tempPlural == 0) {
            // --- Ini ceritanya klo dia cuma bisa 1 alat musik ---
            if (statusPemusik.get(tempIndex) == false) { // Cek status pemusik apakah sudah ada di minggu itu
                statusPemusik.set(tempIndex, true);
                jadwal.get(0).add(pemusik.get(index)); // Buat nambahin di minggu 1
            } else {
                forPrint = false;
            }
        } else {
            for (int i = 0; i < pemusik.size(); i++) {
                if (statusPemusik.get(tempIndex) == false) { // Cek status pemusik apakah sudah ada di minggu itu
                    statusPemusik.set(tempIndex, true);
                    jadwal.get(0).add(pemusik.get(index)); // Buat nambahin di minggu 1
                    forPrint = true;
                    break;
                }
                forPrint = false;
            }
        }

        getJadwalForaWeek(index + 1); // Pemusik selanjutnya
        if (forPrint) {
            String namaAlatMusik = alatMusik.get(tempIndex).getNamaAlat();
            System.out.println(namaAlatMusik + " : " + pemusik.get(index).getNama());
        }
    }

    public static void main(String[] args) {

        jadwal.add(new ArrayList<>());

        // --- Alat Musik ---
        alatMusik.add(new AlatMusik("Gitar"));
        alatMusik.add(new AlatMusik("Bass"));
        alatMusik.add(new AlatMusik("Drum"));
        alatMusik.add(new AlatMusik("Keyboard"));

        // --- Pemusik 1 ---
        pemusik.add(new Pemusik("Marvel"));
        pemusik.get(0).addAlatMusik(alatMusik.get(3));

        // --- Pemusik 2 ---
        pemusik.add(new Pemusik("Jordan"));
        pemusik.get(1).addAlatMusik(alatMusik.get(2));
        pemusik.get(1).addAlatMusik(alatMusik.get(3));

        // --- Pemusik 3 ---
        pemusik.add(new Pemusik("Pikachu"));
        pemusik.get(2).addAlatMusik(alatMusik.get(3));
        pemusik.get(2).addAlatMusik(alatMusik.get(2));

        // --- Pemusik 4 ---
        pemusik.add(new Pemusik("Luigi"));
        pemusik.get(3).addAlatMusik(alatMusik.get(1));

        // --- Pemusik 5 ---
        pemusik.add(new Pemusik("Leon"));
        // pemusik.get(4).addAlatMusik(alatMusik.get(0));
        pemusik.get(4).addAlatMusik(alatMusik.get(3));

        // --- Pemusik 6 ---
        pemusik.add(new Pemusik("Thasya"));
        pemusik.get(5).addAlatMusik(alatMusik.get(3));

        // --- Pemusik 7 ---
        pemusik.add(new Pemusik("Naruto"));
        // pemusik.get(6).addAlatMusik(alatMusik.get(0));
        pemusik.get(6).addAlatMusik(alatMusik.get(2));

        // --- Pemusik 8 ---
        pemusik.add(new Pemusik("Jennifer"));
        pemusik.get(7).addAlatMusik(alatMusik.get(1));
        pemusik.get(7).addAlatMusik(alatMusik.get(2));

        // --- Pemusik 9 ---
        pemusik.add(new Pemusik("Benaya"));
        // pemusik.get(8).addAlatMusik(alatMusik.get(0));
        pemusik.get(8).addAlatMusik(alatMusik.get(1));
        pemusik.get(8).addAlatMusik(alatMusik.get(2));

        // --- Pemusik 10 ---
        pemusik.add(new Pemusik("Lily"));
        // pemusik.get(9).addAlatMusik(alatMusik.get(0));
        pemusik.get(9).addAlatMusik(alatMusik.get(1));
        pemusik.get(9).addAlatMusik(alatMusik.get(2));
        pemusik.get(9).addAlatMusik(alatMusik.get(3));

        initializeStatusPemusik();
        getJadwalForaWeek(0);

    }
}
