/*
 * This source file was generated by the Gradle 'init' task
 */
package tubes;

import tubes.models.AlatMusik;
import tubes.models.Pemusik;
import tubes.models.Status;

public class App {

    static AlatMusik gitar = new AlatMusik("Gitar");
    static AlatMusik keyboard = new AlatMusik("keyboard");
    static AlatMusik bass = new AlatMusik("bass");
    static AlatMusik drum = new AlatMusik("drum");

    public static void generateWeekMusician() {
        getDrum(0);
    }
    
    public static String getDrum(int index) {
        StringBuilder output = new StringBuilder();
        if (index == drum.jumlahPemusik()) { // Klo udah limit pemusik
            return "";
        } else { // Klo belum limit
            if (drum.getListPemusik().get(index).getStatus() != Status.READY) {
                output.append(getDrum(index + 1));
            } else {
                drum.getListPemusik().get(index).setStatus(Status.OCCUPIED);
                output.append("Drum: ").append(drum.getListPemusik().get(index).getNama()).append("\n");
                output.append(getBass(0));
            }

            return output.toString();
        }
    }

    public static String getBass(int index) {
        StringBuilder output = new StringBuilder();
        if (index == bass.jumlahPemusik()) { // Klo udah limit pemusik
            return "";
        } else { // Klo belum limit
            if (bass.getListPemusik().get(index).getStatus() != Status.READY) {
                output.append(getBass(index + 1));
            } else {
                bass.getListPemusik().get(index).setStatus(Status.OCCUPIED);
                output.append("Bass: ").append(bass.getListPemusik().get(index).getNama()).append("\n");
                output.append(getKeyboard(0));
            }

            return output.toString();
        }
    }

    public static String getKeyboard(int index) {
        StringBuilder output = new StringBuilder();
        if (index == keyboard.jumlahPemusik()) { // Klo udah limit pemusik
            return "";
        } else { // Klo belum limit
            if (keyboard.getListPemusik().get(index).getStatus() != Status.READY) {
                output.append(getKeyboard(index + 1));
            } else {
                keyboard.getListPemusik().get(index).setStatus(Status.OCCUPIED);
                output.append("Keyboard: ").append(keyboard.getListPemusik().get(index).getNama()).append("\n");
                output.append(getGitar(0));
            }

            return output.toString();
        }
    }

    public static String getGitar(int index) {
        StringBuilder output = new StringBuilder();
        if (index == gitar.jumlahPemusik()) { // Klo udah limit pemusik
            return "";
        } else { // Klo belum limit
            if (gitar.getListPemusik().get(index).getStatus() != Status.READY) {
                output.append(getGitar(index + 1));
            } else {
                gitar.getListPemusik().get(index).setStatus(Status.OCCUPIED);
                output.append("Gitar: ").append(gitar.getListPemusik().get(index).getNama()).append("\n");
            }

            return output.toString();
        }
    }
    
    public static void main(String[] args) {
        // Drum line
        drum.tambahPemusik(new Pemusik("Adrian"));
        drum.tambahPemusik(new Pemusik("Kevin"));
        drum.tambahPemusik(new Pemusik("Bima"));
        drum.tambahPemusik(new Pemusik("Surya"));
        
        // Bass
        bass.tambahPemusik(new Pemusik("Jordan"));
        bass.tambahPemusik(new Pemusik("Raka"));
        bass.tambahPemusik(new Pemusik("Agung"));
        bass.tambahPemusik(new Pemusik("Yudha"));

        // Keyboard crew
        keyboard.tambahPemusik(new Pemusik("Sarah"));
        keyboard.tambahPemusik(new Pemusik("Viona"));
        keyboard.tambahPemusik(new Pemusik("Leon"));
        keyboard.tambahPemusik(new Pemusik("Maya"));
        
        // Gitar squad
        gitar.tambahPemusik(new Pemusik("Nathalie"));
        gitar.getListPemusik().get(0).setStatus(Status.OCCUPIED);
        gitar.tambahPemusik(new Pemusik("Felix"));
        gitar.tambahPemusik(new Pemusik("Dimas"));
        gitar.tambahPemusik(new Pemusik("Rico"));
        gitar.tambahPemusik(new Pemusik("Aulia"));


        generateWeekMusician();
    }
}
